### ISSUE TITLE
`fh add` is not respecting existing `inputs` structure

### ISSUE THREAD

**Issue by srid** [DeterminateSystems/fh#14]
I ran `fh add srid/haskell-flake` on https://github.com/srid/nixci and this was the result. Note that it has not added haskell-flake under the existing `inputs` attrset; rather created a flat one at top.

```diff
diff --git a/flake.nix b/flake.nix
index 732d5c3..771f181 100644
--- a/flake.nix
+++ b/flake.nix
@@ -1,4 +1,5 @@
 {
+  inputs.haskell-flake.url = "https://flakehub.com/f/srid/haskell-flake/0.4.0.tar.gz";
   inputs = {
     nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
     flake-parts.url = "github:hercules-ci/flake-parts";
```

**Comment by cole-h** [comment]
I agree that the current behavior leaves something to be desired! I plan to fix this soon.

(I used to have a TODO about exactly that but I think I lost it somewhere)

**Comment by cole-h** [comment]
@srid I think I've resolved this issue with https://github.com/DeterminateSystems/fh/pull/19, if you wouldn't mind trying it out!

**Comment by cole-h** [comment]
I just realized, I could just try your reproducer on that branch... lol. This is what I get:

```diff
diff --git a/flake.nix b/flake.nix
index 732d5c3..b016aed 100644
--- a/flake.nix
+++ b/flake.nix
@@ -1,5 +1,6 @@
 {
   inputs = {
+    haskell-flake.url = "https://flakehub.com/f/srid/haskell-flake/0.4.0.tar.gz";
     nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
     flake-parts.url = "github:hercules-ci/flake-parts";
     systems.url = "github:nix-systems/default";

```

I think that's what you were expecting to see!

**Comment by srid** [comment]
> I think that's what you were expecting to see!

Yup.

(Although I'd personally add the new flake at the _end_ of the inputs list)

**Comment by cole-h** [comment]
Adding to the end is a little bit more involved than adding to the top heh. But I might look into making that configurable...

**Comment by cole-h** [comment]
@srid I've implemented support for inserting new flake inputs at the bottom of your existing flake inputs here: https://github.com/DeterminateSystems/fh/pull/25
