### ISSUE TITLE
Docs for public flakehub api

### ISSUE THREAD

**Issue by yajo** [DeterminateSystems/fh#24]
It would be useful for things such as shields.io integration.

**Comment by lucperkins** [comment]
@yajo Which specific operations does shields.io typically require? I can document those first and fill in others later.

**Comment by lucperkins** [comment]
@yajo Ah, sorry, just checked the shields.io issue linked here 😄 At the moment, we don't really have any API endpoint for that but that's a good idea.

**Comment by grahamc** [comment]
[![FlakeHub](https://img.shields.io/endpoint?url=https://flakehub.com/f/DeterminateSystems/fh/badge)](https://flakehub.com/flake/DeterminateSystems/fh)

We've got shields!

Here's an example:

```markdown
[![FlakeHub](https://img.shields.io/endpoint?url=https://flakehub.com/f/DeterminateSystems/fh/badge)](https://flakehub.com/flake/DeterminateSystems/fh)
```

**Comment by grahamc** [comment]
I'm going to go ahead and close this. We don't have a stable public API right now, but we do have shields integration :).

Feel free to open a new one to represent a stable public API!
