### ISSUE TITLE
`fh init` doesn't detect JavaScript project

### ISSUE THREAD

**Issue by kpine** [DeterminateSystems/fh#40]
Running `fh init` in a JS project doesn't produce any prompts or add any node/yarn packages.

Is this a result of a typo here?

https://github.com/DeterminateSystems/fh/blob/c5643ff58fcebb9d0afdb509f30fb774092ff1c8/src/cli/cmd/init/handlers/javascript.rs#L11

Presumably, `package.jspn` -> `package.json`?

**Comment by grahamc** [comment]
Oh no! 🤦

**Comment by grahamc** [comment]
Thank you, I hope that fixes it up for you 😓
