### ISSUE TITLE
Unsupported Tarball

### ISSUE THREAD

**Issue by lecoqjacob** [DeterminateSystems/fh#46]
Whenever I add FlakeHub dependencies to my flake config, If i run `nix flake update`, my config starts spitting out errors saying:

![image](https://github.com/DeterminateSystems/fh/assets/9278174/5708564f-78d6-4d4c-aba9-6828d786cb0e)

**Comment by lucperkins** [comment]
Upgrading to 2.18.1 should take care of that immediately: https://flakehub.com/docs#i-got-error-unsupported-tarball-input-attribute-rev-or--error-unsupported-tarball-input-attribute-lastmodified-what-do-these-errors-mean
