### ISSUE TITLE
fh status crashes when not authenticated

### ISSUE THREAD

**Issue by flexiondotorg** [DeterminateSystems/fh#64]
## Error
```
Error: 
   0: Could not open /home/martin/.config/flakehub/auth; have you run `fh login`?
   1: No such file or directory (os error 2)
```

## Metadata
|key|value|
|--|--|
|**version**|0.1.6|
|**os**|linux|
|**arch**|x86_64|

**Comment by cole-h** [comment]
Does https://github.com/DeterminateSystems/fh/pull/68 improve this for you?
