### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by fvkd** [DeterminateSystems/fh#81]
## Error
```
Error: 
   0: Request was unsuccessful
   1: HTTP status client error (400 Bad Request) for url (https://api.flakehub.com/cli/status)
```

## Metadata
|key|value|
|--|--|
|**version**|0.1.6|
|**os**|linux|
|**arch**|x86_64|

**Comment by cole-h** [comment]
You'll need to update `fh` to at least v0.1.8. FlakeHub now requires all requests contain a user-agent, and old versions of the `fh` CLI unfortunately did not set a user-agent.
