### ISSUE TITLE
Cannot run fh init as instructed by Zero-to-Nix

### ISSUE THREAD

**Issue by yacinehmito** [DeterminateSystems/fh#86]
FYI, as I was following zero-to-nix, I ran `nix run "https://flakehub.com/f/DeterminateSystems/fh/*.tar.gz" -- init` ([as instructed](https://zero-to-nix.com/start/init-flake)) and got this error message:

```
error: builder for '/nix/store/sigk6kxwq1rqldkrb41ysva45bqmjbp4-fh-20231111-9ee4cc0-0.1.8.drv' failed with exit code 101;
       last 10 log lines:
       >     cli::cmd::convert::test::test_nixpkgs_from_registry
       >     cli::cmd::eject::test::flakehub_nixpkgs_to_github
       >     cli::cmd::eject::test::flakehub_to_github
       >     cli::cmd::eject::test::test_flake8_eject
       >     cli::cmd::eject::test::versioned_flakehub_to_github
       >
       > test result: FAILED. 7 passed; 9 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.50s
       >
       > error: test failed, to rerun pass `--bin fh`
       > /nix/store/zv9jfmqy3lwknq5y3mxhp99r9n50ykjl-stdenv-darwin/setup: line 1608: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/sigk6kxwq1rqldkrb41ysva45bqmjbp4-fh-20231111-9ee4cc0-0.1.8.drv'.
```

[Output of nix log /nix/store/sigk6kxwq1rqldkrb41ysva45bqmjbp4-fh-20231111-9ee4cc0-0.1.8.drv](https://github.com/DeterminateSystems/fh/files/13466194/logs.txt)

**Comment by yacinehmito** [comment]
Works fine with 0.1.6 but not 0.1.7 (and not 0.1.8, as seen above).

**Comment by lucperkins** [comment]
@yacinehmito Which system are you on? Any other context you can provide? I haven't been able to reproduce.

**Comment by lucperkins** [comment]
I wonder if it's this: https://github.com/NixOS/nixpkgs/issues/214822

**Comment by yacinehmito** [comment]
I am on macOS. Ventura 13.6 specifically, and I have nix-darwin installed. What command can I run to provide you with more info?

**Comment by lucperkins** [comment]
@cole-h Does this ring a bell to you? I've been able to reproduce this.

**Comment by cole-h** [comment]
Could you try using `nix run "github:DeterminateSystems/fh/disable-some-tests-on-darwin" -- init` and tell me if that fixes it for you?
